// ============================================================
// menu.js - handles the main menu: song list, difficulty select,
// and switching screens. Talks to game.js via window.RhythmGame
// ============================================================

// List every chart json available here. Each entry points to a
// chart file generated by tools/chart_generator.py.
// Convention: assets/audio/music/<SongFolder>/<SongFolder>.json (+ .mp3
// sitting right next to it in the same folder).
const SONG_LIST = [
  { id: "eastward", name: "EastWard", chart: "assets/audio/music/EastWard/EastWard.json" },
  { id: "rei", name: "Rei dos demônios", chart: "assets/audio/music/Rei/Rei.json" },
];

let selectedDifficulty = "normal";
let selectedSongEntry = null;

function showScreen(id) {
  document.querySelectorAll(".screen").forEach(s => s.classList.remove("active"));
  document.getElementById(id).classList.add("active");
}

function populateSongList() {
  const select = document.getElementById("song-select");
  select.innerHTML = "";
  SONG_LIST.forEach(song => {
    const opt = document.createElement("option");
    opt.value = song.id;
    opt.textContent = song.name;
    select.appendChild(opt);
  });
}

function initMenu() {
  populateSongList();

  document.querySelectorAll(".diff-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".diff-btn").forEach(b => b.classList.remove("selected"));
      btn.classList.add("selected");
      selectedDifficulty = btn.dataset.diff;
    });
  });

  document.getElementById("play-btn").addEventListener("click", async () => {
    const songId = document.getElementById("song-select").value;
    selectedSongEntry = SONG_LIST.find(s => s.id === songId);
    if (!selectedSongEntry) return;

    showScreen("game-screen");
    await window.RhythmGame.start(selectedSongEntry, selectedDifficulty);
  });

  document.getElementById("back-to-menu-btn").addEventListener("click", () => {
    showScreen("menu-screen");
  });
}

document.addEventListener("DOMContentLoaded", initMenu);
